### ISSUE TITLE
Crash when use different proxy

### ISSUE THREAD

**Issue by BurningTeng** [BurningTeng/Bill#1]
When I use different proxy to start new sign, there is a crash.
`
var task = Task.Run(() =>
{
    SignUtils su = new();
    su.StartProxyServer();
    su.SetProxyPort(8888);

    su.exit = false;
    su.Sign(listPerson[0].name, listPerson[0].email, listPerson[0].password, 8888);
    Console.WriteLine("打卡完成");
    su.StopProxyServer();
});
task.Wait();

Console.WriteLine("Finish first proxy");

await Task.Delay(10*1000);

task = Task.Run(() =>
{
    SignUtils su = new();

    su.StartProxyServer();
    su.SetProxyPort(9999);
    su.exit = false;
    su.Sign(listPerson[0].name, listPerson[0].email, listPerson[0].password, 9999);
    Console.WriteLine("打卡完成");
    su.StopProxyServer();
    //取消代理。连续3次启动的话就失败。第二次代理服务器起不来。

});
task.Wait();
`
错误:
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
https://vortex.data.microsoft.com/collect/v1
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot start the driver service on http://localhost:58024/)
 ---> OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:58024/
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor()
   at SignSystem.SignUtils.Sign(String name, String email, String password, Int32 port)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)

**Comment by BurningTeng** [comment]
Set endpoint at Ip 0.0.0.0 and port: 9999 as System HTTPS Proxy
Starting MSEdgeDriver 99.0.1150.46 (a1c1ea02160226bf4a0831a74f06de8edf55ffcf) on port 55836
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
https://vortex.data.microsoft.com/collect/v1
https://edge.microsoft.com/componentupdater/api/v1/update?cup2key=5:PQ9IJgx6tvqLC-IbRFlquAoa8fIvVoUcakZ8z1lkHFg&cup2hreq=370f84862c9bbc018e8c70f48ae97a641c2397e93a3e6f061c9eeb5dc5760a63
http://msedge.b.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/baf51d01-2f04-404a-8cfe-55b3e72cc178?P1=1649862957&P2=404&P3=2&P4=MV4Uy%2fSp9UtzFCRCExzEqRxTE%2b8%2bOiWZjwm9fdmmyRtbZsZNfy22WfZaP6MtW0xm6PIWSsdjK%2fHhqZxL%2faYAIA%3d%3d
由于目标计算机积极拒绝，无法连接。 [::ffff:127.0.0.1]:8888 (localhost:8888)
https://cn.bing.com/RelatedSearch?addfeaturesnoexpansion=relatedsearch&mkt=zh-CN
https://cxcs.microsoft.net/api/settings/zh-CN/xml/settings-tipset?release=20h1&sku=Professional&platform=desktop
